// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class InsuranceSuiteTest
{
    private IWebDriver driver;
    public IDictionary<string, object> vars { get; private set; }
    private IJavaScriptExecutor js;
    [SetUp]
    public void SetUp()
    {
        driver = new ChromeDriver();
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<string, object>();
    }
    [TearDown]
    protected void TearDown()
    {
        driver.Quit();
    }

    [Test]
    public void insurance_30and4and0_NoAddress()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/");
        driver.Manage().Window.Size = new System.Drawing.Size(1346, 708);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.CssSelector(".card:nth-child(1) > div > .form-group:nth-child(1)")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Urvish");
        driver.FindElement(By.Id("lastName")).Click();
        driver.FindElement(By.Id("lastName")).SendKeys("Sabhaya");
        driver.FindElement(By.Id("city")).Click();
        driver.FindElement(By.Id("city")).SendKeys("Cambridge");
        driver.FindElement(By.Id("postalCode")).Click();
        driver.FindElement(By.Id("postalCode")).SendKeys("N3H 0C6");
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).SendKeys("444-444-4444");
        driver.FindElement(By.Id("email")).Click();
        driver.FindElement(By.Id("email")).SendKeys("u@gmail.com");
        driver.FindElement(By.CssSelector(".container")).Click();
        driver.FindElement(By.CssSelector(".col-md-6")).Click();
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("30");
        driver.FindElement(By.Id("experience")).Click();
        driver.FindElement(By.Id("experience")).SendKeys("4");
        driver.FindElement(By.Id("accidents")).Click();
        driver.FindElement(By.Id("accidents")).SendKeys("0");
        driver.FindElement(By.Id("btnSubmit")).Click();
        {
            var element = driver.FindElement(By.Id("btnSubmit"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Perform();
        }
        {
            var element = driver.FindElement(By.TagName("body"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element, 0, 0).Perform();
        }
        Assert.That(driver.FindElement(By.Id("address-error")).Text, Is.EqualTo("Address is required"));
    }
    [Test]
    public void insurance_25and0and2_ZeroDrvExp()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/");
        driver.Manage().Window.Size = new System.Drawing.Size(1346, 708);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Urvish");
        driver.FindElement(By.Id("lastName")).SendKeys("Sabhaya");
        driver.FindElement(By.Id("address")).SendKeys("4-420 Linden Drive, Cambridge");
        driver.FindElement(By.Id("city")).SendKeys("Kitchener");
        driver.FindElement(By.Id("postalCode")).SendKeys("N3H 0C6");
        driver.FindElement(By.Id("phone")).SendKeys("437-988-4586");
        driver.FindElement(By.Id("email")).SendKeys("urvishsabhaya@gmail.com");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("25");
        driver.FindElement(By.Id("experience")).Click();
        driver.FindElement(By.Id("experience")).SendKeys("0");
        driver.FindElement(By.Id("accidents")).Click();
        driver.FindElement(By.Id("accidents")).SendKeys("2");
        driver.FindElement(By.CssSelector("body")).Click();
        driver.FindElement(By.Id("addForm")).Click();
        driver.FindElement(By.Id("btnSubmit")).Click();
        {
            string value = driver.FindElement(By.Id("finalQuote")).GetAttribute("value");
            Assert.That(value, Is.EqualTo("$4000"));
        }
    }
    [Test]
    public void insurance_25and3and0_AllFields()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/");
        driver.Manage().Window.Size = new System.Drawing.Size(1382, 744);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Urvish");
        driver.FindElement(By.Id("lastName")).Click();
        driver.FindElement(By.Id("lastName")).SendKeys("Sabhaya");
        driver.FindElement(By.Id("address")).Click();
        driver.FindElement(By.Id("address")).SendKeys("4-420 Linden Drive, Cambridge");
        driver.FindElement(By.Id("city")).SendKeys("Kitchener");
        driver.FindElement(By.Id("postalCode")).SendKeys("N3H 0C6");
        driver.FindElement(By.Id("phone")).SendKeys("437-988-4586");
        driver.FindElement(By.Id("email")).SendKeys("urvishsabhaya@gmail.com");
        driver.FindElement(By.Id("email")).Click();
        driver.FindElement(By.CssSelector(".card:nth-child(3) > .card-header")).Click();
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("25");
        driver.FindElement(By.Id("experience")).Click();
        driver.FindElement(By.Id("experience")).SendKeys("3");
        driver.FindElement(By.Id("accidents")).Click();
        driver.FindElement(By.Id("accidents")).SendKeys("0");
        driver.FindElement(By.Id("finalQuote")).Click();
        driver.FindElement(By.Id("finalQuote")).Click();
        driver.FindElement(By.Id("btnSubmit")).Click();
        {
            string value = driver.FindElement(By.Id("finalQuote")).GetAttribute("value");
            Assert.That(value, Is.EqualTo("$2500"));
        }
    }
    [Test]
    public void insurance_25and3and0_NoFirstName()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/");
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("lastName")).SendKeys("Sabhaya");
        driver.FindElement(By.Id("address")).SendKeys("4-420 Linden Drive, Cambridge");
        driver.FindElement(By.Id("city")).SendKeys("Kitchener");
        driver.FindElement(By.Id("postalCode")).SendKeys("N3H 0C6");
        driver.FindElement(By.Id("phone")).SendKeys("437-988-4586");
        driver.FindElement(By.Id("email")).SendKeys("urvishsabhaya@gmail.com");
        driver.FindElement(By.Id("age")).SendKeys("25");
        driver.FindElement(By.Id("experience")).SendKeys("3");
        driver.FindElement(By.Id("accidents")).SendKeys("0");
        driver.FindElement(By.Id("btnSubmit")).Click();
        Assert.That(driver.FindElement(By.Id("firstName-error")).Text, Is.EqualTo("First Name is required"));
    }
    [Test]
    public void insurance_26and2and1_NoCity()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/");
        driver.Manage().Window.Size = new System.Drawing.Size(1366, 728);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Urvish");
        driver.FindElement(By.Id("lastName")).SendKeys("Sabhaya");
        driver.FindElement(By.Id("address")).SendKeys("4-420 Linden Drive, Cambridge");
        driver.FindElement(By.Id("postalCode")).SendKeys("N3H 0C6");
        driver.FindElement(By.Id("phone")).SendKeys("437-988-4586");
        driver.FindElement(By.Id("email")).SendKeys("urvishsabhaya@gmail.com");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("26");
        driver.FindElement(By.Id("experience")).Click();
        driver.FindElement(By.Id("experience")).SendKeys("2");
        driver.FindElement(By.Id("accidents")).Click();
        driver.FindElement(By.Id("accidents")).SendKeys("1");
        driver.FindElement(By.Id("btnSubmit")).Click();
        Assert.That(driver.FindElement(By.Id("city-error")).Text, Is.EqualTo("City is required"));
    }
    [Test]
    public void insurance_26and3and0_NoLastName()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/");
        driver.Manage().Window.Size = new System.Drawing.Size(1366, 728);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Urvish");
        driver.FindElement(By.Id("address")).Click();
        driver.FindElement(By.Id("address")).SendKeys("4-420 Linden Drive");
        driver.FindElement(By.Id("city")).SendKeys("Cambridge");
        driver.FindElement(By.Id("postalCode")).SendKeys("N3H 0C6");
        driver.FindElement(By.Id("phone")).SendKeys("4379884586");
        driver.FindElement(By.Id("email")).SendKeys("urvishsabhaya@yahoo.com");
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("phone")).SendKeys("437-988-4586");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("26");
        driver.FindElement(By.Id("experience")).Click();
        driver.FindElement(By.Id("experience")).SendKeys("3");
        driver.FindElement(By.Id("accidents")).Click();
        driver.FindElement(By.Id("accidents")).SendKeys("0");
        driver.FindElement(By.Id("btnSubmit")).Click();
        driver.FindElement(By.CssSelector(".card:nth-child(1) > div:nth-child(2)")).Click();
        Assert.That(driver.FindElement(By.Id("lastName-error")).Text, Is.EqualTo("Last Name is required"));
    }
    [Test]
    public void insurance_27and3and0_InvalidPhone()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/");
        driver.Manage().Window.Size = new System.Drawing.Size(1366, 728);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Urvish");
        driver.FindElement(By.Id("lastName")).Click();
        driver.FindElement(By.Id("lastName")).SendKeys("Sabhaya");
        driver.FindElement(By.Id("address")).Click();
        driver.FindElement(By.Id("address")).SendKeys("4-420 Linden Drive, Cambridge");
        driver.FindElement(By.Id("city")).SendKeys("Kitchener");
        driver.FindElement(By.Id("postalCode")).SendKeys("N3H 0C6");
        driver.FindElement(By.Id("phone")).SendKeys("4379884586");
        driver.FindElement(By.Id("email")).SendKeys("urvishsabhaya@gmail.com");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("27");
        driver.FindElement(By.Id("experience")).Click();
        driver.FindElement(By.Id("experience")).SendKeys("3");
        driver.FindElement(By.Id("accidents")).Click();
        driver.FindElement(By.Id("accidents")).SendKeys("0");
        driver.FindElement(By.Id("btnSubmit")).Click();
        {
            var element = driver.FindElement(By.Id("btnSubmit"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Perform();
        }
        {
            var element = driver.FindElement(By.TagName("body"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element, 0, 0).Perform();
        }
        Assert.That(driver.FindElement(By.Id("phone-error")).Text, Is.EqualTo("Phone Number must follow the patterns 111-111-1111 or (111)111-1111"));
    }
    [Test]
    public void insurance_28and3and0_InvalidEmail()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/");
        driver.Manage().Window.Size = new System.Drawing.Size(1366, 728);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Urvish");
        driver.FindElement(By.Id("lastName")).SendKeys("Sabhaya");
        driver.FindElement(By.Id("address")).SendKeys("4-420 Linden Drive, Cambridge");
        driver.FindElement(By.Id("city")).SendKeys("Kitchener");
        driver.FindElement(By.Id("postalCode")).SendKeys("N3H 0C6");
        driver.FindElement(By.Id("phone")).SendKeys("437-988-4586");
        driver.FindElement(By.Id("email")).SendKeys("urvishsabhaya");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("28");
        driver.FindElement(By.CssSelector(".card-body")).Click();
        driver.FindElement(By.Id("experience")).Click();
        driver.FindElement(By.Id("experience")).SendKeys("3");
        driver.FindElement(By.Id("accidents")).Click();
        driver.FindElement(By.Id("accidents")).SendKeys("0");
        driver.FindElement(By.Id("btnSubmit")).Click();
        driver.FindElement(By.Id("email-error")).Click();
        driver.FindElement(By.Id("email-error")).Click();
        {
            var element = driver.FindElement(By.Id("email-error"));
            Actions builder = new Actions(driver);
            builder.DoubleClick(element).Perform();
        }
        driver.FindElement(By.Id("email-error")).Click();
        Assert.That(driver.FindElement(By.Id("email-error")).Text, Is.EqualTo("Must be a valid email address"));
    }
    [Test]
    public void insurance_29and5and0_Rate2500()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/");
        driver.Manage().Window.Size = new System.Drawing.Size(1346, 708);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.CssSelector(".card:nth-child(1) > div:nth-child(2)")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Urvish");
        driver.FindElement(By.Id("lastName")).SendKeys("Sabhaya");
        driver.FindElement(By.Id("address")).SendKeys("4-420 Linden Drive, Cambridge");
        driver.FindElement(By.Id("city")).SendKeys("Kitchener");
        driver.FindElement(By.Id("postalCode")).SendKeys("N3H 0C6");
        driver.FindElement(By.Id("phone")).SendKeys("437-988-4586");
        driver.FindElement(By.Id("email")).SendKeys("urvishsabhaya@gmail.com");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("29");
        driver.FindElement(By.Id("experience")).Click();
        driver.FindElement(By.Id("experience")).SendKeys("5");
        driver.FindElement(By.Id("accidents")).Click();
        driver.FindElement(By.Id("accidents")).SendKeys("0");
        driver.FindElement(By.Id("btnSubmit")).Click();
        {
            string value = driver.FindElement(By.Id("finalQuote")).GetAttribute("value");
            Assert.That(value, Is.EqualTo("$2500"));
        }
    }
    [Test]
    public void insurance_29and10and0_Rate1800()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/");
        driver.Manage().Window.Size = new System.Drawing.Size(1346, 708);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Urvish");
        driver.FindElement(By.Id("lastName")).SendKeys("Sabhaya");
        driver.FindElement(By.Id("address")).SendKeys("4-420 Linden Drive, Cambridge");
        driver.FindElement(By.Id("city")).SendKeys("Kitchener");
        driver.FindElement(By.Id("postalCode")).SendKeys("N3H 0C6");
        driver.FindElement(By.Id("phone")).SendKeys("437-988-4586");
        driver.FindElement(By.Id("email")).SendKeys("urvishsabhaya@gmail.com");
        driver.FindElement(By.CssSelector(".card-body")).Click();
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("29");
        driver.FindElement(By.Id("experience")).Click();
        driver.FindElement(By.Id("experience")).SendKeys("10");
        driver.FindElement(By.Id("accidents")).Click();
        driver.FindElement(By.Id("accidents")).SendKeys("0");
        driver.FindElement(By.Id("btnSubmit")).Click();
        {
            string value = driver.FindElement(By.Id("finalQuote")).GetAttribute("value");
            Assert.That(value, Is.EqualTo("$1800"));
        }
    }
    [Test]
    public void insurance_35and17and1_InvalidPostalCode()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/");
        driver.Manage().Window.Size = new System.Drawing.Size(1366, 728);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Urvish");
        driver.FindElement(By.Id("lastName")).SendKeys("Sabhaya");
        driver.FindElement(By.Id("address")).SendKeys("4-420 Linden Drive, Cambridge");
        driver.FindElement(By.Id("city")).SendKeys("Kitchener");
        driver.FindElement(By.Id("postalCode")).SendKeys("NBBBBB");
        driver.FindElement(By.Id("phone")).SendKeys("437-988-4586");
        driver.FindElement(By.Id("email")).SendKeys("urvishsabhaya@gmail.com");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("35");
        driver.FindElement(By.Id("experience")).Click();
        driver.FindElement(By.Id("experience")).SendKeys("17");
        driver.FindElement(By.Id("accidents")).Click();
        driver.FindElement(By.Id("accidents")).SendKeys("1");
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("btnSubmit")).Click();
        driver.FindElement(By.Id("btnSubmit")).Click();
        driver.FindElement(By.CssSelector(".col-md-2")).Click();
        driver.FindElement(By.Id("postalCode-error")).Click();
        driver.FindElement(By.Id("postalCode-error")).Click();
        {
            var element = driver.FindElement(By.Id("postalCode-error"));
            Actions builder = new Actions(driver);
            builder.DoubleClick(element).Perform();
        }
        Assert.That(driver.FindElement(By.Id("postalCode-error")).Text, Is.EqualTo("Postal Code must follow the pattern A1A 1A1"));
    }
    [Test]
    public void insurance_36and5and0_NoAge()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/");
        driver.Manage().Window.Size = new System.Drawing.Size(1346, 708);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("lastName")).SendKeys("Sabhaya");
        driver.FindElement(By.Id("address")).SendKeys("4-420 Linden Drive, Cambridge");
        driver.FindElement(By.Id("city")).SendKeys("Kitchener");
        driver.FindElement(By.Id("postalCode")).SendKeys("N3H 0C6");
        driver.FindElement(By.Id("phone")).SendKeys("437-988-4586");
        driver.FindElement(By.Id("email")).SendKeys("urvishsabhaya@gmail.com");
        driver.FindElement(By.Id("firstName")).SendKeys("Urvish");
        driver.FindElement(By.Id("experience")).Click();
        driver.FindElement(By.Id("experience")).SendKeys("5");
        driver.FindElement(By.Id("accidents")).Click();
        driver.FindElement(By.Id("accidents")).SendKeys("0");
        driver.FindElement(By.Id("phone")).Click();
        driver.FindElement(By.Id("btnSubmit")).Click();
        Assert.That(driver.FindElement(By.Id("age-error")).Text, Is.EqualTo("Age (>=16) is required"));
    }
    [Test]
    public void insurance_37and8and0_NoAccidents()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/");
        driver.Manage().Window.Size = new System.Drawing.Size(1366, 728);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Urvish");
        driver.FindElement(By.Id("lastName")).SendKeys("Sabhaya");
        driver.FindElement(By.Id("address")).SendKeys("4-420 Linden Drive, Cambridge");
        driver.FindElement(By.Id("city")).SendKeys("Kitchener");
        driver.FindElement(By.Id("postalCode")).SendKeys("N3H 0C6");
        driver.FindElement(By.Id("phone")).SendKeys("437-988-4586");
        driver.FindElement(By.Id("email")).SendKeys("urvishsabhaya@gmail.com");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("37");
        driver.FindElement(By.Id("experience")).Click();
        driver.FindElement(By.Id("experience")).SendKeys("8");
        driver.FindElement(By.Id("btnSubmit")).Click();
        {
            var element = driver.FindElement(By.Id("btnSubmit"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Perform();
        }
        {
            var element = driver.FindElement(By.TagName("body"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element, 0, 0).Perform();
        }
        driver.FindElement(By.CssSelector(".card-body > .form-group:nth-child(3)")).Click();
        Assert.That(driver.FindElement(By.Id("accidents-error")).Text, Is.EqualTo("Number of accidents is required"));
    }
    [Test]
    public void insurance_45and9and0_NoDrvExp()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/");
        driver.Manage().Window.Size = new System.Drawing.Size(1366, 728);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Urvish");
        driver.FindElement(By.Id("lastName")).SendKeys("Sabhaya");
        driver.FindElement(By.Id("address")).SendKeys("4-420 Linden Drive, Cambridge");
        driver.FindElement(By.Id("city")).SendKeys("Kitchener");
        driver.FindElement(By.Id("postalCode")).SendKeys("N3H 0C6");
        driver.FindElement(By.Id("phone")).SendKeys("437-988-4586");
        driver.FindElement(By.Id("email")).SendKeys("urvishsabhaya@gmail.com");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("45");
        driver.FindElement(By.Id("accidents")).Click();
        driver.FindElement(By.Id("accidents")).SendKeys("0");
        driver.FindElement(By.CssSelector(".container")).Click();
        driver.FindElement(By.Id("btnSubmit")).Click();
        driver.FindElement(By.CssSelector(".card-body")).Click();
        Assert.That(driver.FindElement(By.Id("experience-error")).Text, Is.EqualTo("Years of experience is required"));
    }
    [Test]
    public void insurance_45and9and5_MoreAccidents()
    {
        driver.Navigate().GoToUrl("http://localhost/prog8170a04/");
        driver.Manage().Window.Size = new System.Drawing.Size(1346, 708);
        driver.FindElement(By.CssSelector(".btn")).Click();
        driver.FindElement(By.Id("firstName")).Click();
        driver.FindElement(By.Id("firstName")).SendKeys("Urvish");
        driver.FindElement(By.Id("lastName")).SendKeys("Sabhaya");
        driver.FindElement(By.Id("address")).SendKeys("4-420 Linden Drive, Cambridge");
        driver.FindElement(By.Id("city")).SendKeys("Kitchener");
        driver.FindElement(By.Id("postalCode")).SendKeys("N3H 0C6");
        driver.FindElement(By.Id("phone")).SendKeys("437-988-4586");
        driver.FindElement(By.Id("email")).SendKeys("urvishsabhaya@gmail.com");
        driver.FindElement(By.Id("age")).Click();
        driver.FindElement(By.Id("age")).SendKeys("45");
        driver.FindElement(By.Id("experience")).Click();
        driver.FindElement(By.Id("experience")).SendKeys("9");
        driver.FindElement(By.Id("accidents")).Click();
        driver.FindElement(By.Id("accidents")).SendKeys("5");
        driver.FindElement(By.Id("btnSubmit")).Click();
        {
            string value = driver.FindElement(By.Id("finalQuote")).GetAttribute("value");
            Assert.That(value, Is.EqualTo("No Insurance for you!!  Too many accidents - go take a course!"));
        }
    }
}
